### ISSUE TITLE
--help/man for nix-store 

### ISSUE THREAD

**Issue by ShalokShalom** [t184256/nix-on-droid#177]
Hi :)

I issued 'nix-store' without any operator, and it tells me to launch 'nix-store --help' instead. 
The result of this commando: 

```command 'man nix-store' failed: No such file or directory. ```

Seems like there is no man page for it, while the app itself refers to it and offers the --help handle.

**Comment by t184256** [comment]
Oh, IMO Linux UX is notorious for taking precise low-level error messages and dragging them through so many contexts that they become fully out of touch. So until investigated with more scrutiny, I won't be surprised if it turns out it's coming from

* a missing manpage
* a missing `man` command
* a missing `$PAGER`
* a missing fallback hardcoded pager like `less`
* a missing interpreter on a wrapper around a pager or `man`
* some missing file in `/etc` that no sane system would omit so nobody bothered with more specific error messages
* a missing hardcoded FHS path in an error path no normal system would reach
* or possibly a dozen other possibly missing things =)

Let me do a clean install and do some guesswork.

**Comment by t184256** [comment]
Seems like it's the `man` command that's missing. I don't remember it being needed some releases ago.

Now the question is what do we do about it. We already have a precedent of bending over to satisfy `nix --help`'s hidden dependencies:

https://github.com/t184256/nix-on-droid/blob/07c4406897104c7be56094b0865e4c37aa72ec8f/modules/environment/path.nix#L49

so I see at least three possible directions:

1. install `man` unconditionally (makes minimal install larger)
2. ask nixpkgs to packaging Nix the Nix way with an explicit dependency on `man` (and maybe even on a pager as well since we are at it?)
3. do nothing and let the users guess it means they're missing `man`

I vaguely remember that fresh Nix should need no man, just lowdown and a pager for documentation rendering, but this probably applies only to the new CLI.

**Comment by Gerschtli** [comment]
I would prefer number 2 if the nix maintainers are okay with this. This package currently has undeclared runtime dependencies which should happen at all. Or they could at least improve the error messages for missing man oder less commands.

**Comment by ShalokShalom** [comment]
Man seems to be pretty obvious as a choice for something like a default setup.

**Comment by ShalokShalom** [comment]
Vim is actually the only tool I dont care about in this case. How much would the rest of the stuff cost and are you concerned about the costs on the device itself, or the download size?

Cant add that much. Can we simply ask on download, what users want and deliver accordingly?
Like. _Do you like to add a line of basic tools, eg  man, gzip and grep?_

**Comment by ShalokShalom** [comment]
Better ask as a question.

**Comment by t184256** [comment]
I respectfully disagree, I don't think this warrants going on a slippery slope of creating an interactive installer.

I've filed a Nix issue for starters, since Nix reference packaging also doesn't seem to pull in `man`.
