### ISSUE TITLE
TODO: provide overlay to fix packages for android

### ISSUE THREAD

**Issue by Gerschtli** [t184256/nix-on-droid#23]
Provide an overlay to fix/patch some packages like https://github.com/termux/termux-packages does with htop for example: https://github.com/termux/termux-packages/tree/master/packages/htop.

These patched packages should be available through the nix-on-droid binary cache.

**Comment by puffnfresh** [comment]
I've started an overlay here, starting with htop:

https://github.com/puffnfresh/nix-files/blob/master/nix-on-droid/termux-overlay.nix

I tried openssh, but it looks like I struggle to build it at all because of `/var/empty` existing:

https://github.com/puffnfresh/nix-files/blob/droid/openssh/nix-on-droid/termux-overlay.nix

**Comment by Gerschtli** [comment]
Nice! Maybe we should also work on an overlay for nix itself as indicated in this issue: https://github.com/NixOS/nix/issues/3237

**Comment by t184256** [comment]
Landed @Gerschtli's overlay for `htop` in 93d081c, fixes to other packages should use it as an example.
