### ISSUE TITLE
installation does not continoue - unpacking channels ..

### ISSUE THREAD

**Issue by InLaw** [t184256/nix-on-droid#236]
![IMG_6107](https://user-images.githubusercontent.com/16096709/206218420-4071179c-0bd7-45de-b639-152655edd744.JPG)

Samsung M52 - Android 13 One Ui 5.0 - Google System update July 01

**Comment by t184256** [comment]
Wait, I don't have much more advice. Maybe one: "acquire wakelock" in notification might help if your system is aggressively preventing it from executing.

**Comment by InLaw** [comment]
that is what I did.
30 Minutes, 3 hours? .. how long till I know it is not working?

**Comment by Gerschtli** [comment]
On my device it takes ~30min for the whole bootstrap. Unfortunately, `nix-channel` does not provide more output than this. Maybe it got stuck, so maybe clean app data and try again?

**Comment by InLaw** [comment]
now it starts building ..

**Comment by InLaw** [comment]
takes hours ..

**Comment by t184256** [comment]
This is outstandingly slow, even 30 minutes is.

Are you using adopted storage (combining sd card with built-in storage)? Is your storage near full? Is network speed severely throttled or something?

**Comment by MatrixManAtYrService** [comment]
For a sense of progress you can go to settings -> storage -> other apps -> Nix and watch the `User data` field grow. 

In my case...
| time since saying `N` to "do you want to set it up with flakes" (minutes) | User Data Size (MB) |
|:--|:--|
| 0 | 108 |
| 2 | 162 |
| 5 | 220 |
| 7 | 248 |
| 10 | 291 |
| 14 | 335 |
| 18 | 366 |
| 22 | 366 |
| 25 | 366 |
```
Installing first Nix-on-droid generation...
Building activation package...
bash-5.1$
```
| time since saying `N` to "do you want to set it up with flakes" (minutes) | User Data Size (MB) |
|:--|:--|
| 29 | 847 |
```
Executing activation script...
```



I didn't measure it, but it seemed pretty fast on my home internet connection. Now I'm doing it at school and it's slower.

**Comment by nona-mousy** [comment]
"Nothing works" so i'm just here to say hi. 😁

~Having~ Had the same issue, where it (channels, not flakes) was stuck for more than 45min after which I always aborted. Uninstalled and reinstalled it for a couple of times and somehow now it finished after ~6min now. Magic! 🪄

Nix-on-Droid: 0.118.0_v0.3.3_nix
Android: 13 (Coral) - GrapheneOS 2023072600 - on Google Pixel 4XL
