### ISSUE TITLE
termux-open / termux-toast

### ISSUE THREAD

**Issue by lypanov** [t184256/nix-on-droid#84]
I'm looking to switch to nix-on-droid given how quick you were to fix the spacemacs bug mentioned in another issue here.

Unfortunately a core part of my work flow involves the use of termux-open and termux-toast. Do you have any plans to work on improving this area? I'd love to help in any way possible (mostly on device, but I imagine that will provide too many constraints for these features).

Do you have any ideas how this could be implemented? Specifically - I assume some communication channel between a program in the running nix distro and the outer Android termux-terminal fork would be needed right?

**Comment by t184256** [comment]
For this one I have a simple and uninspiring answer: I have no idea how this Android-bordering magic works in Termux, and I have no plans for exploring this Android-boundary, mostly because I have pretty much zero Android programming experience. I'll be glad to test and accept relevant pull requests into nix-on-droid and nix-on-droid-app, maybe help on the nix-on-droid side, esp. differences with Termux. But I definitely don't have implementing/porting the Android part in my plans.

**Comment by lypanov** [comment]
Dug into the way termux-api works and found this: https://github.com/termux/termux-api#how-api-calls-are-made-through-the-termux-api-helper-binary

**Comment by t184256** [comment]
Sounds like the bulk of the job would be baking the termux-api Java stuff (that Termux folks ship separately) into nix-on-droid-app. =/

**Comment by lypanov** [comment]
Note: I'm still on TermuxArch not yet migrated to nix-on-droid. I've worked around my need for a termux-toast equivalent by getting xfce4-notifyd working.

I've also found a temporary work around for the termux-open need by sshing open requests via a running Termux instance. If the day comes that these workarounds don't suffice. I'll reopen this ticket and start work on it.
